In [16]:
import numpy as np

## Creating a list

In [17]:
pole_1d = np.array([0, 5, 10, 15, 20])
print(pole_1d)

print(" ")

pole_2d = np.array([[1.0, 3, 5, 7],
                    [2, 4, 6, 8]])
print(pole_2d)

print(" ")

pole_3d = np.array([[[1, 1], [2, 2]],
                    [[3, 3], [4, 4]],
                    [[5, 5], [6, 6]]])
print(pole_3d)

[ 0  5 10 15 20]
 
[[1. 3. 5. 7.]
 [2. 4. 6. 8.]]
 
[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]]


In [18]:
pole_1d

array([ 0,  5, 10, 15, 20])

## List properties

In [19]:
print("(size) Broj na elementi:", pole_2d.size)  # number of elements
print("(ndim) Broj na dimenzii:", pole_2d.ndim)  # number of dimensions
print("(shape) Elementi po dimenzija:", pole_2d.shape)  # number of elements in a dimension in tuple format
print("(nbytes) Golemina vo bajti:", pole_2d.nbytes)  # size in bytes
print("(dtype) Tip na podatoci:", pole_2d.dtype)  # type of data

(size) Broj na elementi: 8
(ndim) Broj na dimenzii: 2
(shape) Elementi po dimenzija: (2, 4)
(nbytes) Golemina vo bajti: 64
(dtype) Tip na podatoci: float64


## dtype - data types

In [20]:
pole_1d = np.array([0, 5], dtype='S3')
print(pole_1d.dtype)
pole_2d = np.array([[1.0, 3], [2, 4]], dtype=np.int64)
print(pole_2d.dtype)

|S3
int64


In [21]:
pole_1d_int = pole_2d.astype(np.int32)
print(pole_1d_int.dtype)
pole_2d_float = pole_2d.astype('f')
print(pole_2d_float.dtype)


int32
float32


# Functions for creating arrays

In [22]:
# 1D niza od 4 nuli 
nuli = np.zeros(4)
print(nuli)


[0. 0. 0. 0.]


In [23]:
# 2x3 niza od edinici od tipot int16 
edinici = np.ones((2, 3), dtype=np.int16)
print(edinici)


[[1 1 1]
 [1 1 1]]


In [25]:
# 2x2 niza od vrednosti 3
dvojki = np.full((2, 2), 3)
print(dvojki)


[[3 3]
 [3 3]]


In [27]:
# 2x2 niza od nuli so edinici na glavanta dijagonala
identitet = np.identity(2, dtype='i')  # dtype = int
print(identitet)


[[1 0]
 [0 1]]


In [28]:
rastechka = np.arange(0, 12, 3)
print(rastechka)

[0 3 6 9]


In [29]:
# 2x3 niza od slucjani broevi vo opseg 0 do 1
sluchajni = np.random.random(size=(2, 3))
print(sluchajni)
# 2x5 niza od celi slucjani broevi vo opseg 10 do 20
sluchajni_celi = np.random.randint(10, 20, size=(2, 5))
print(sluchajni_celi)
# 1D niza od slucjani broevi so normalna raspredelba
# so sr. vred. 0 i std. dev. 2
slucjani_normalna = np.random.normal(0, 4, 6)
print(slucjani_normalna)


[[0.20715577 0.09765307 0.22855334]
 [0.82507554 0.71498324 0.46346673]]
[[13 12 16 18 14]
 [19 12 15 15 15]]
[-1.80625285 -6.91840463 -0.52428779  2.25396398  4.63818371  1.99435409]


## Пристап до податоци/елементи

In [32]:
pole_1d = np.array([2, 4, 6, 8, 10, 12, 14])
print(pole_1d[2])
print(pole_1d[1:5:3])  # start:end:step [1, 1+3=4,] -> [4, 10]
print(pole_1d[::-2])

6
[ 4 10]
[14 10  6  2]


In [33]:
pole_2d = np.array([[0, 10, 20, 30, 40],
                    [50, 60, 70, 80, 90],
                    [100, 110, 120, 130, 140],
                    [150, 160, 170, 180, 190]])
print(pole_2d[1, 2])  # element od redica 1 i kolona 2
print(pole_2d[1:3, 1:4])  # site elementi od redica 1 do 2 i kolona 1 do 3
print(pole_2d[1:, 1:4:2])  # site elementi od redica 1 do kraj i sekoj vtor od kolona 1 do 3 
print(pole_2d[2:, :4])  # site elementi od redica 2 do rkaj i od prva kolona do kolona 3
print(pole_2d[::2, :])  # site elementi od sekoja vtora redica od site koloni
print(pole_2d[:, -1])  # site elementi od poslednata kolona 

70
[[ 60  70  80]
 [110 120 130]]
[[ 60  80]
 [110 130]
 [160 180]]
[[100 110 120 130]
 [150 160 170 180]]
[[  0  10  20  30  40]
 [100 110 120 130 140]]
[ 40  90 140 190]


## Филтрирање

In [34]:
print("Pole:", pole_1d)
dellivi_so_4 = (pole_1d % 4 == 0)  # True ako elementot e delliv so 4
print("Maska:", dellivi_so_4)
print("Pole[maska]:", pole_1d[dellivi_so_4])

Pole: [ 2  4  6  8 10 12 14]
Maska: [False  True False  True False  True False]
Pole[maska]: [ 4  8 12]


In [35]:
# pechatenje na broevi koi ne se dellivi so 4
print(pole_1d[pole_1d % 4 > 0])

[ 2  6 10 14]


In [36]:
denovi = np.array(["Ponedelnik", "Vtornik", "Sreda", "Chetvrtok", "Petok", "Sabota", "Nedela"])
temperaturi = np.array([[17, 19, 15, 10, 21, 22, 12],
                        [27, 31, 29, 28, 35, 36, 30]])
print(temperaturi[:, (denovi == "Vtornik") | (denovi == "Chetvrtok")])

# (denovi == "Vtornik") | (denovi == "Chetvrtok") ->
# [False, True, False, True, False, False, False]

[[19 10]
 [31 28]]


In [39]:
niski_temperaturi = temperaturi < 20
print("2D maska:\n", niski_temperaturi)
print("1D rezultat:\n", temperaturi[niski_temperaturi])

2D maska:
 [[ True  True  True  True False False  True]
 [False False False False False False False]]
1D rezultat:
 [17 19 15 10 12]


In [40]:
denovi == "Vtornik"

array([False,  True, False, False, False, False, False])

## Пристап со низи од индекси

In [42]:
print(pole_1d[[6, 1, 4]])  # elementi so indeks 6, 1 i 4
print(pole_2d[[3, 1]])  # elementi od red so indeks 3 i 1

[14  4 10]
[[150 160 170 180 190]
 [ 50  60  70  80  90]]


## Комбиниран пристап

In [47]:
print(pole_2d[1, [4, 2, 1]])  # elementi od red 1 i koloni 4 i 2
print(pole_2d[[1, 0], 1::2])  # elementi od red 1 i 0 i sekoja vtora kolona pocnjvajki od kolona 1

[90 70 60]
[[60 80]
 [10 30]]


In [48]:
print(pole_2d[[0, 2, 1], [3, 1, 4]])  # element so koordinati (0,3), (2,1) и (1,4)

[ 30 110  90]


In [49]:
selektirani_redici = pole_2d[[0, 2, 1]]
print(selektirani_redici[:, [3, 1, 4]])

[[ 30  10  40]
 [130 110 140]
 [ 80  60  90]]


In [50]:
print(pole_2d[[0, 2, 1]][:, [3, 1, 4]])  # matrica so red 0, 2, 1 i kolona 3, 1, 4

[[ 30  10  40]
 [130 110 140]
 [ 80  60  90]]


## Промена на вредности/елементи

In [58]:
pole_2d = np.random.randint(0, 10, size=(3, 4))
pole_2d[0, 0] = 1
print(pole_2d)


[[1 8 6 9]
 [3 4 2 0]
 [9 8 3 5]]


In [59]:
pole_2d[:, 0] = 2  #site elementi na kolona 0 dobivaat vrednost 2
pole_2d[:, 1] = [1, 2, 3]  #elementite na kolona 1 dobivaat vrednost 1, 2 i 3, soodvetno
print(pole_2d)

[[2 1 6 9]
 [2 2 2 0]
 [2 3 3 5]]


In [60]:
pole_2d[1, 2:] = 3  #site elementi na red 1, pochnuvajki od kolona 2 dobivaat vrednost 3
pole_2d[2, :] = [10, 20, 30, 40]  #elementite na red 2 dobivaat vrednost 10, 20, 30 i 40, soodvetno
print(pole_2d)

[[ 2  1  6  9]
 [ 2  2  3  3]
 [10 20 30 40]]


In [61]:
pole_2d[pole_2d == 2] = 22
print(pole_2d)

[[22  1  6  9]
 [22 22  3  3]
 [10 20 30 40]]


## Погледи и копии

In [63]:
pole_2d = np.array([[0, 10, 20, 30],
                    [40, 50, 60, 70],
                    [80, 90, 100, 110]])
opseg = pole_2d[1, :]  # opseg e pogled sostaven od elementite na red 1
opseg[:] = 33  # promenata na elementite na opseg se afektira vo pole_2d
print("Opseg:\n", opseg)
print("Originalna niza:\n", pole_2d)


Opseg:
 [33 33 33 33]
Originalna niza:
 [[  0  10  20  30]
 [ 33  33  33  33]
 [ 80  90 100 110]]


In [64]:
pole_2d = np.array([[0, 10, 20, 30],
                    [40, 50, 60, 70],
                    [80, 90, 100, 110]])
opseg = pole_2d[1, :].copy()  # opseg e kopja od elementite na red 1
opseg[:] = 33  # promenata na elementite na opseg NE se afektira vo pole_2d
print("Opseg:\n", opseg)
print("Originalna niza:\n", pole_2d)

Opseg:
 [33 33 33 33]
Originalna niza:
 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## Промена на димензии и облик

In [65]:
rastechka_2d = np.arange(15).reshape(3, 5)
print(rastechka_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [66]:
print(rastechka_2d.reshape(5, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [68]:
# if the number of elements is unknown, we use -1 for that dimension
pole_nepoznata_dim = np.arange(18).reshape(2, 3, -1)
print("Pole:\n", pole_nepoznata_dim)
print("Elementi po dimenzija:\n", pole_nepoznata_dim.shape)

Pole:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Elementi po dimenzija:
 (2, 3, 3)


In [70]:
print(rastechka_2d.reshape(-1)) # if we use -1, we make the array one-dimensional (flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Спојување и разделување

In [73]:
pole1 = np.array([[1, 2],
                  [3, 4]])
pole2 = np.array([[10, 20],
                  [30, 40]])
print("Spojuvanje po oska 0:\n", np.concatenate((pole1, pole2)))  # axis=0 (vertical)
print("Spojuvanje po oska 1:\n", np.concatenate((pole1, pole2), axis=1)) # (horizontal)

Spojuvanje po oska 0:
 [[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]


In [76]:
print("Spojuvanje po oska 0:\n", np.stack((pole1, pole2)))
print("Spojuvanje po oska 1:\n", np.stack((pole1, pole2), axis=1))

Spojuvanje po oska 0:
 [[[ 1  2]
  [ 3  4]]

 [[10 20]
  [30 40]]]
Spojuvanje po oska 1:
 [[[ 1  2]
  [10 20]]

 [[ 3  4]
  [30 40]]]


In [78]:
print("Spojuvanje po oska 0:\n", np.dstack((pole1, pole2)))
print("Spojuvanje po oska 1:\n", np.hstack((pole1, pole2)))
print("Spojuvanje po oska 1:\n", np.hstack((pole1, pole2)))
print(np.vstack((pole1, pole2)).shape)
print(np.hstack((pole1, pole2)).shape)

Spojuvanje po oska 0:
 [[[ 1 10]
  [ 2 20]]

 [[ 3 30]
  [ 4 40]]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
Spojuvanje po oska 1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
(4, 2)
(2, 4)


In [80]:
pole_2d = np.arange(1, 13).reshape(3, 4)
print("Originalna niza:\n", pole_2d)
razdeleno_pole = np.split(pole_2d, 2, axis=1)  # razdeli po koloni
print("Prva niza:\n", razdeleno_pole[0])
print("Vtora niza:\n", razdeleno_pole[1])

Originalna niza:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Prva niza:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Vtora niza:
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [81]:
# razdeli po redici, axis=0, razdeli od redica 1
razdeleno_pole = np.split(pole_2d, [1])
print("Prva niza:\n", razdeleno_pole[0])
print("Vtora niza:\n", razdeleno_pole[1])

Prva niza:
 [[1 2 3 4]]
Vtora niza:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
razdeleno_pole = np.vsplit(pole_2d, [2])
print("Prva niza vsplit:\n", razdeleno_pole[0])
print("Vtora niza vsplit:\n", razdeleno_pole[1])
razdeleno_pole = np.hsplit(pole_2d, 2)
print("Prva niza hsplit:\n", razdeleno_pole[0])
print("Vtora niza hsplit:\n", razdeleno_pole[1])

Prva niza vsplit:
 [[1 2 3 4]
 [5 6 7 8]]
Vtora niza vsplit:
 [[ 9 10 11 12]]
Prva niza hsplit:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Vtora niza hsplit:
 [[ 3  4]
 [ 7  8]
 [11 12]]


## Пребарување на елементи

In [86]:
pole_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
pole_2d = np.arange(1, 13).reshape(3, 4)
print(np.where(pole_2d % 3 == 0))

(array([0, 1, 2, 2], dtype=int64), array([2, 1, 0, 3], dtype=int64))


In [85]:
print(pole_2d[pole_2d % 3 == 0])

[ 3  6  9 12]


In [87]:
print(np.where(pole_2d % 3 == 0, pole_2d, 0))

[[ 0  0  3  0]
 [ 0  6  0  0]
 [ 9  0  0 12]]


## Подредување

In [89]:
pole = np.random.randint(10, size=(3, 4))
print("Originalna niza:\n", pole)
print("Podreduvanje po dimenzija 1:\n", np.sort(pole))
print("Podreduvanje po dimenzija 0:\n", np.sort(pole, axis=0))
print("Podreduvanje na izramneta niza:\n", np.sort(pole, axis=None)) # sorted one-dimensional array

Originalna niza:
 [[2 6 7 7]
 [8 2 2 4]
 [4 5 8 1]]
Podreduvanje po dimenzija 1:
 [[2 6 7 7]
 [2 2 4 8]
 [1 4 5 8]]
Podreduvanje po dimenzija 0:
 [[2 2 2 1]
 [4 5 7 4]
 [8 6 8 7]]
Podreduvanje na izramneta niza:
 [1 2 2 2 4 4 5 6 7 7 8 8]


## Аритметика

In [91]:
a = np.array([[4, 5, 6],
              [3, 2, 1]])
b = np.array([[7, 8, 9],
              [6, 5, 4]])

print("a + b =\n", a + b)
print("1 / a =\n", 1 / a)
print("b ** 2 + 1=\n", b ** 2 + 1)

a + b =
 [[11 13 15]
 [ 9  7  5]]
1 / a =
 [[0.25       0.2        0.16666667]
 [0.33333333 0.5        1.        ]]
b ** 2 + 1=
 [[50 65 82]
 [37 26 17]]


In [92]:
A = np.array([[4, 5, 6],
              [3, 2, 1],
              [1, 2, 3]])
print("A*A (mnozhenje na matrici):\n", A.dot(A))


A*A (mnozhenje na matrici):
 [[37 42 47]
 [19 21 23]
 [13 15 17]]


In [93]:
c = np.array([2, 2, 2])
print(a + c)
print(a + c.T)

[[6 7 8]
 [5 4 3]]
[[6 7 8]
 [5 4 3]]


## Емитување 

In [95]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10])
print(A.shape)
print(B.shape)
print(A)
print(B)

(2, 3)
(1,)
[[1 2 3]
 [4 5 6]]
[10]


In [96]:
print("A+B\n", A + B)

A+B
 [[11 12 13]
 [14 15 16]]


In [98]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 11, 12])
print(A.shape)
print(B.shape)
print(A)
print(B)

(2, 3)
(3,)
[[1 2 3]
 [4 5 6]]
[10 11 12]


In [99]:
print("A+B\n", A + B)

A+B
 [[11 13 15]
 [14 16 18]]


In [103]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 11])
print(A.shape)
print(B.shape)
print(A)
print(B)

(2, 3)
(2,)
[[1 2 3]
 [4 5 6]]
[10 11]


In [104]:
print("A+B\n", A + B)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [105]:
A = np.array([[4, 5, 6],
              [3, 2, 1],
              [1, 2, 3]])
print("A*A (mnozhenje na matrici):\n", A.dot(A))


A*A (mnozhenje na matrici):
 [[37 42 47]
 [19 21 23]
 [13 15 17]]


In [106]:
A.transpose()

array([[4, 3, 1],
       [5, 2, 2],
       [6, 1, 3]])

## Математички функции

In [108]:
a = 10 * np.random.random(size=(1, 4))
print("Niza:\n", a)
cel_del, frakcija = np.modf(a)
print("Cel del:\n", cel_del)
print("Frakcija:\n", frakcija)

Niza:
 [[2.23885057 9.52456865 0.47024139 6.73962277]]
Cel del:
 [[0.23885057 0.52456865 0.47024139 0.73962277]]
Frakcija:
 [[2. 9. 0. 6.]]


### Aggregate Functions

In [109]:
z = np.array([[3, 6, 1],
              [4, 9, 5]])
print("Min i max na cela niza:\n", np.min(z), np.max(z))
print("Min i max po oska 1:\n", np.min(z, axis=1), np.max(z, axis=1))
print("Indeksi na min i max po oska 1:\n", np.argmin(z, axis=1), np.argmax(z, axis=1))


Min i max na cela niza:
 1 9
Min i max po oska 1:
 [1 4] [6 9]
Indeksi na min i max po oska 1:
 [2 0] [1 1]


In [110]:
print("Suma na cela niza:\n", z.sum())
print("Suma po oska 0:\n", z.sum(axis=0))
print("Kumulativna suma:\n", z.cumsum())
print("Kumulativna suma po oska 1:\n", z.cumsum(axis=1))


Suma na cela niza:
 28
Suma po oska 0:
 [ 7 15  6]
Kumulativna suma:
 [ 3  9 10 14 23 28]
Kumulativna suma po oska 1:
 [[ 3  9 10]
 [ 4 13 18]]
