Да се вклучи пакетот numpy.

In [1]:
import numpy as np

#Креирање на низи

Да се креира еднодимензионално  поле pole_1d користејќи листа од 4 целобројни вредности. Да се креира дводимензионално поле pole_2d користејќи листа од 3 листи со по 4 целобројни вредности. 
Да се креира тридимензионално поле pole_3d користејќи листа од листа од 4 листи со по 4 текстуални вредности. 

In [46]:
pole_1d = np.array([1, 2, 3, 4])
print(pole_1d)
pole_2d = np.array([[2, 3, 4, 5],
                    [6, 7, 8, 9],
                    [9, 10, 11, 12]])
print(pole_2d)
pole_3d =np.array([[['a','b','c'],['d','e','f']],
                   [['g','h','i'],['j','l','m']]])
print(pole_3d)

[1 2 3 4]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [ 9 10 11 12]]
[[['a' 'b' 'c']
  ['d' 'e' 'f']]

 [['g' 'h' 'i']
  ['j' 'l' 'm']]]


#Својства на листа

Да се испчатат големината, бојот на димензиите, обликот, бројот на бајти што ги зафаќаат елементите и нивниот тип на податоци за листата pole_2d.

In [47]:
print("Broj na elementi:",pole_2d.size)
print("Broj na dimenzii:",pole_2d.ndim)
print("Elementi po dimenzija:",pole_2d.shape)
print("Golemina vo bajti:",pole_2d.nbytes)
print("Tip na podatoci:",pole_2d.dtype)

Broj na elementi: 12
Broj na dimenzii: 2
Elementi po dimenzija: (3, 4)
Golemina vo bajti: 96
Tip na podatoci: int64


#Тип на податоци

Да се креира поле pole_1d од листа со 4 целобројни врености така што истите ќе бидат децимални броеви кои зафаќаат 8 бајти. 
Да се креира поле pole_2d од листа од две листи со по две дцимални врендости, така што истите ќе бидат текстулани низи од по максимум 5 знаци. 

In [48]:
pole_1d = np.array([0, 5, 10, 20], dtype=np.float64)
print(pole_1d.dtype)
pole_2d = np.array([[234, 0.3], [2, 4.6]], dtype = 'S5')
print(pole_2d.dtype)

float64
|S5


Да се креира поле pole_1d_str од полето pole_1d, така што неговите елементи ќе претставуваат низи од максимум 4 знаци. Да се креира поле pole_2d_float од полето pole_2d, така што неговите елементи ќе бидат децимални броеви кои зафаќаагт 2 бајти. 

In [49]:
pole_1d_str = pole_2d.astype('S4')
print(pole_1d_str.dtype)
pole_2d_float=pole_2d.astype(np.float16)
print(pole_2d_float.dtype)


|S4
float16


In [50]:
print(pole_1d_str)

[[b'234' b'0.3']
 [b'2' b'4.6']]


#Функции за креирање низи

Да се креира поле со 3 редици и 4 колони со елементи со вредност 5.

In [51]:

petki = np.full((3,4),5)
print(petki)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Да се креира поле со 2 редици и 3 колони со елементи со вредност 0 кои ќе бидат цели броеви што зафаќаат 8 бајти.


In [52]:
# 2x3 niza od edinici od tipot int16 
nuli = np.zeros((2,3), dtype=np.int16)
print(nuli)


[[0 0 0]
 [0 0 0]]


Да се креира поле со 5 редици и 5 колони каде сите елементи ќе имаат вредност 0, освен елементите од главната дијагонала кои ќе имаат вредност 5.


In [53]:
# 2x2 niza od nuli so edinici na glavanta dijagonala
identitet = np.identity(5)
print(identitet)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Да се креира еднодимензионално поле со елементи добиени како опсег од 5 до 45, каде секој елемент се резликува за 5.


In [54]:
rastechka = np.arange(5,50,5)
print(rastechka)

[ 5 10 15 20 25 30 35 40 45]


Да се креира поле sluchajni со 3 редици и 5 колони со елементи со случајна вредност во опсегот од 0 до 1.

Да се креира поле sluchajni со 3 редици и 3 колони со цели елементи со случајна вредност во опсегот од -10 до 10.

Да се креира еднодимензионално поле sluchajni_normalna со 10 елементи чии елементи имаат случајна вредност добиена со нормална распределба со среднда вредност 5 и стандарнда девијација 2. 



In [55]:

sluchajni=np.random.random(size=(3,5))
print(sluchajni)
sluchajni_celi = np.random.randint(-10, 10, size=(3,3))
print(sluchajni_celi)
slucjani_normalna = np.random.normal(5,2,10)
print(slucjani_normalna)


[[0.48802129 0.95235706 0.13077905 0.09544864 0.90070798]
 [0.19626735 0.28841908 0.00991766 0.1429665  0.40926157]
 [0.19117675 0.43040493 0.31988801 0.4150483  0.89077147]]
[[-6 -7  5]
 [ 0 -2  7]
 [ 8 -9  6]]
[5.82781396 1.60928942 3.94658588 3.89691116 5.15873692 5.06129921
 7.63901343 4.35372311 5.96960236 2.49138393]


#Пристап до податоци

Да се креира 2Д поле со димензија 5х4, чии елементи ќе имаат растечки вредности од 0 до 19 користејќи го методот reshape. Потоа да се пристапи до елементот со координати 3,0, сите елементи од последните две редици и секоја втора колона, секој елемент од претпоследната редица.

In [56]:
pole_2d=np.arange(0,20).reshape(5,4)
print(pole_2d)
print(pole_2d[3,0])  
print(pole_2d[2::,::2]) # site elementi od redica 1 do 2 i kolona 1 do 3
print(pole_2d[:,-2]) # site elementi od poslednata kolona 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
12
[[ 8 10]
 [12 14]
 [16 18]]
[ 2  6 10 14 18]


#Филтрирање

Да се испечати маска за пристап на елементи од полето sluchajni_celi која има вредност True за сите негативни броеви.
Да се испечатат сите негативни броеви од sluchajni_celi користејќи ја маската. 
Да се испеатат сите негативни броеви директно со постаување на услов во делот за иднекси.

In [57]:
print("Pole:",sluchajni_celi)
negativni = (sluchajni_celi < 0) 
print("Maska:",negativni)
print("Pole[maska]:",sluchajni_celi[negativni])
print("Pole[uslov]]:",sluchajni_celi[sluchajni_celi < 0])

Pole: [[-6 -7  5]
 [ 0 -2  7]
 [ 8 -9  6]]
Maska: [[ True  True False]
 [False  True False]
 [False  True False]]
Pole[maska]: [-6 -7 -2 -9]
Pole[uslov]]: [-6 -7 -2 -9]


#Низи од индекси

Да се пристапи до елементите со индекс 1 и 2 од полето pole_1d. 

Да се пристапи до колона 3 и 2 од полето pole_2d

In [58]:
print(pole_1d[[1, 2]]) 
print(pole_2d[:,[3, 2]])    



[ 5. 10.]
[[ 3  2]
 [ 7  6]
 [11 10]
 [15 14]
 [19 18]]


#Комбиниран пристап

Да се испечатата редовите од полето pole_2d во обратен редослед, но да се прикажат само колона 1 и 3.

In [59]:
print(pole_2d[::-1, [1, 3]])    # elementi od red 1 i koloni 4 i 2


[[17 19]
 [13 15]
 [ 9 11]
 [ 5  7]
 [ 1  3]]


Да се испечатат елементите со координати (3, 4) и (0, 1) од полето pole_2d.

In [60]:
print(pole_2d[[3, 2], [0, 1]]) 


[12  9]


Да се испечатат елементите од редовите 3 и 2 и колоните 0 и 1. 

In [61]:
print(pole_2d[[3, 2]][:,[0, 1]]) 

[[12 13]
 [ 8  9]]


#Промена на вредности

Да се додели вредноста на првата редица на последната редица на полето pole_2d

In [62]:
pole_2d[0,:] = pole_2d[-1,:] 
print(pole_2d)

[[16 17 18 19]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Да се додели вредност 0 на исте елементи на полето pole_2d поголеми од 10.

In [63]:
pole_2d[pole_2d>10]=0
print(pole_2d)

[[ 0  0  0  0]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


#Погледи и копии

Да се креира копија на редовите 1 и 2 полето pole_2d кои ќе можат независно да се менуваат. Елементите од копијата да се помножат со 2 и потоа да се прикаже содржината на двете полиња.

In [64]:
opseg=pole_2d[[1,2],:].copy() 
opseg=opseg * 2
print("Opseg:\n",opseg)
print("Originalna niza:\n",pole_2d)

Opseg:
 [[ 8 10 12 14]
 [16 18 20  0]]
Originalna niza:
 [[ 0  0  0  0]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


#Промена на димензии

Да се креира поле со 5 колони и соодветен број на редици тргнувајќи од низа од 95 елементи.

In [65]:
pole_nepoznata_dim=np.arange(95).reshape(-1,5)
print("Pole:\n", pole_nepoznata_dim)
print("Elementi po dimenzija:\n", pole_nepoznata_dim.shape)



Pole:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]]
Elementi po dimenzija:
 (19, 5)


Полето pole_2d  да се претвори во еднодимензионално.

In [66]:
print(pole_2d.flatten())

[ 0  0  0  0  4  5  6  7  8  9 10  0  0  0  0  0  0  0  0  0]


#Спојување и разделување

Да се креираат две 3х3 полиња и да се спојат вертикално и хоризнотално со додавање на нова димензија.

In [67]:
pole1 = np.random.randint(0,10, (3,3))
pole2 = np.random.randint(0,10, (3,3))
print(pole1)
print(pole2)
print("Spojuvanje so po oska 0 so nova dimenzija:\n",np.stack((pole1, pole2), axis=0))
print("Dimenzii:\n",np.stack((pole1, pole2), axis=0).shape)
print("Spojuvanje po oska 1 so nova dimenzija:\n",np.stack((pole1, pole2), axis=1))
print("Dimenzii:\n",np.stack((pole1, pole2), axis=1).shape)

[[8 8 6]
 [6 0 5]
 [0 3 2]]
[[4 1 2]
 [0 6 1]
 [6 2 5]]
Spojuvanje so po oska 0 so nova dimenzija:
 [[[8 8 6]
  [6 0 5]
  [0 3 2]]

 [[4 1 2]
  [0 6 1]
  [6 2 5]]]
Dimenzii:
 (2, 3, 3)
Spojuvanje po oska 1 so nova dimenzija:
 [[[8 8 6]
  [4 1 2]]

 [[6 0 5]
  [0 6 1]]

 [[0 3 2]
  [6 2 5]]]
Dimenzii:
 (3, 2, 3)


Да се креираат две 3х3 полиња и да се спојат вертикално и хоризнотално без додавање на нова димензија.

In [68]:
print(pole1)
print(pole2)
print("Spojuvanje so po oska 0 bez nova dimenzija:\n",np.vstack((pole1, pole2)))
print("Dimenzii:\n",np.vstack((pole1, pole2)).shape)
print("Spojuvanje po oska 1 bez nova dimenzija:\n",np.hstack((pole1, pole2)))
print("Dimenzii:\n",np.hstack((pole1, pole2)).shape)

[[8 8 6]
 [6 0 5]
 [0 3 2]]
[[4 1 2]
 [0 6 1]
 [6 2 5]]
Spojuvanje so po oska 0 bez nova dimenzija:
 [[8 8 6]
 [6 0 5]
 [0 3 2]
 [4 1 2]
 [0 6 1]
 [6 2 5]]
Dimenzii:
 (6, 3)
Spojuvanje po oska 1 bez nova dimenzija:
 [[8 8 6 4 1 2]
 [6 0 5 0 6 1]
 [0 3 2 6 2 5]]
Dimenzii:
 (3, 6)


Да се спојат pole1 и pole2 хоризонтално, а потоа од полето да се добијат 3 полиња со ист број на елементи.

In [69]:
print(pole1)
print(pole2)
spoeno_pole = np.hstack((pole1, pole2))
print("Horizontalno spoeno pole:\n",spoeno_pole)
razdeleno_pole=np.split(spoeno_pole,3, axis=1) # razdeli po koloni
print("Prvo pole:\n",razdeleno_pole[0])
print("Vtoro pole:\n",razdeleno_pole[1])
print("Treto pole:\n",razdeleno_pole[2])

[[8 8 6]
 [6 0 5]
 [0 3 2]]
[[4 1 2]
 [0 6 1]
 [6 2 5]]
Horizontalno spoeno pole:
 [[8 8 6 4 1 2]
 [6 0 5 0 6 1]
 [0 3 2 6 2 5]]
Prvo pole:
 [[8 8]
 [6 0]
 [0 3]]
Vtoro pole:
 [[6 4]
 [5 0]
 [2 6]]
Treto pole:
 [[1 2]
 [6 1]
 [2 5]]


Полето spoeno_pole да се раздели на три полиња каде колоните на разделба ќе бидат 1 и 4.

In [70]:
razdeleno_pole=np.split(spoeno_pole,[1, 4], axis=1) # razdeli po koloni
print("Prvo pole:\n",razdeleno_pole[0])
print("Vtoro pole:\n",razdeleno_pole[1])
print("Treto pole:\n",razdeleno_pole[2])

Prvo pole:
 [[8]
 [6]
 [0]]
Vtoro pole:
 [[8 6 4]
 [0 5 0]
 [3 2 6]]
Treto pole:
 [[1 2]
 [6 1]
 [2 5]]


#Подредување

Да се креира поле со случајни целни броеви со димензија 6х3, и потоа да се подреди по двете оски. Да се подредат сите елементи во 1Д низа.

In [71]:
pole=np.random.randint(10,size=(6,3))
print("Originalna niza:\n",pole)
print("Podreduvanje po dimenzija 1:\n",np.sort(pole))
print("Podreduvanje po dimenzija 0:\n",np.sort(pole, axis=0))
print("Podreduvanje na izramneta niza:\n",np.sort(pole, axis=None))

Originalna niza:
 [[9 7 9]
 [0 0 6]
 [8 9 1]
 [7 3 0]
 [1 5 8]
 [1 8 8]]
Podreduvanje po dimenzija 1:
 [[7 9 9]
 [0 0 6]
 [1 8 9]
 [0 3 7]
 [1 5 8]
 [1 8 8]]
Podreduvanje po dimenzija 0:
 [[0 0 0]
 [1 3 1]
 [1 5 6]
 [7 7 8]
 [8 8 8]
 [9 9 9]]
Podreduvanje na izramneta niza:
 [0 0 0 1 1 1 3 5 6 7 7 8 8 8 8 9 9 9]


#Аритметика

Да се пресмета изразот (1 + A)/B ако А има димензија 4х3, а B има димензија 1x3. 

In [72]:
A = np.arange(12).reshape(4,3)
B = np.arange(1,4).reshape(1,3)
print("A = \n", A)
print("B = \n", B)
print("(1 + A)/B =\n", (1 + A)/B)




A = 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B = 
 [[1 2 3]]
(1 + A)/B =
 [[ 1.   1.   1. ]
 [ 4.   2.5  2. ]
 [ 7.   4.   3. ]
 [10.   5.5  4. ]]


#Емитување 

In [73]:
print(np.zeros((1,3)))

[[0. 0. 0.]]


Да се напише програма која ќе ги чита димензиите на две полиња и ќе испечати дали е можно емитување кај полиња со тие димензии.
1х3 и 3x3.

In [74]:
ax = input("Vnesete ja prvata dimenzija na A\n")
ay = input("Vnesete ja vtorata dimenzija na A\n")
bx = input("Vnesete ja prvata dimenzija na B\n")
by = input("Vnesete ja vtorata dimenzija na B\n")
A=np.zeros((int(ax),int(ay)))
B=np.zeros((int(bx),int(by)))
try:
  C=A+B
  print("dimenziite {} i {} SE kompatibilni za emituvanjue. Rezultatot kje ima obilik {}".format(A.shape, B.shape, C.shape))
except:
  print("dimenziite {} i {} NE se kompatibilni za emituvanjue".format(A.shape, B.shape))

Vnesete ja prvata dimenzija na A
1
Vnesete ja vtorata dimenzija na A
5
Vnesete ja prvata dimenzija na B
3
Vnesete ja vtorata dimenzija na B
4
dimenziite (1, 5) i (3, 4) NE se kompatibilni za emituvanjue


#Математички функции

Да се креира низа 3х6 со нормална распределба и средна вредност 0 (произволна стандарнда девијација). Потоа да се најдат знаците на елементите

In [75]:
a=np.random.normal(0,100, size=(3,6))
print("Niza:\n",a)
znaci = np.sign(a)
print("Znaci:\n",znaci)


Niza:
 [[  33.6381019    28.17006779   65.50080492  -42.9763943   -14.60046769
    43.85887889]
 [ 133.74490334  -33.53885728   24.60422834   -9.03319501  -68.59999818
   -13.70803026]
 [-307.80795488   -3.83985923  216.59520901 -166.72183071  -17.62204601
   -50.40965778]]
Znaci:
 [[ 1.  1.  1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1.]]


Од претходната 2д низа да се најдат најголемиот цел број помал и најмалиот број поголем од вредноста на секој елемент.


In [76]:
print("Najgolem pomal:\n",np.floor(a))
print("Najmal pogolem:\n",np.ceil(a))

Najgolem pomal:
 [[  33.   28.   65.  -43.  -15.   43.]
 [ 133.  -34.   24.  -10.  -69.  -14.]
 [-308.   -4.  216. -167.  -18.  -51.]]
Najmal pogolem:
 [[  34.   29.   66.  -42.  -14.   44.]
 [ 134.  -33.   25.   -9.  -68.  -13.]
 [-307.   -3.  217. -166.  -17.  -50.]]


Да се испечати сумата на елементи на полетоа а по двете димензии и сумата на сите елементи.

In [77]:
print(":\n",a)
print("Suma po oska 0:\n",np.sum(a,axis=0))
print("Suma po oska 1:\n",np.sum(a,axis=1))
print("Suma na site elementi:\n",np.sum(a))

:
 [[  33.6381019    28.17006779   65.50080492  -42.9763943   -14.60046769
    43.85887889]
 [ 133.74490334  -33.53885728   24.60422834   -9.03319501  -68.59999818
   -13.70803026]
 [-307.80795488   -3.83985923  216.59520901 -166.72183071  -17.62204601
   -50.40965778]]
Suma po oska 0:
 [-140.42494965   -9.20864872  306.70024227 -218.73142003 -100.82251187
  -20.25880915]
Suma po oska 1:
 [ 113.5909915    33.46905095 -329.8061396 ]
Suma na site elementi:
 -182.74609714600922
